WIP: Updated code
qld-gov-au/foodpantry-kyfb pull request #2
Opened 2020-10-20 04:36 UTC by DanielTurner

Since we are working agile the code is always in a WIP state until the project is deemed done.

* Updated all the javascript code
* all json/ files for form for backup (Added)
* package.json (Updated)
* Added postinstall to keep the parceljs working (Added)
* button-group.js manages the navigation (Added)
* formio-wrapper.js - This will be moved to NPM once we are happy with the included functionality this de-couples this from formio. (Added)
* topics-list.js - Controls the topics. (Added)
* index.html & index.js - is the app shell (Updated)
* styles - (Updated)
* resources/ - embedded html inside of formio (Updated & Added)
* test/ - Unit tests covering javascript functionality.

2020-10-20 04:39 UTC, DanielTurner commented
This doesn't relate to any one ticket as the tickets assume full functionality.

2020-10-20 22:27 UTC, ThrawnCA requested changes

2020-10-20 22:27 UTC, ThrawnCA commented on src/components/topics-list.js
> +            title: 'Recieve food',
Misspelled "Receive"

2020-10-20 22:27 UTC, ThrawnCA commented on src/components/topics-list.js
> +              'https://api.forms.platforms.qld.gov.au/fesrqwsyzlbtegd/recievefood',
Misspelled "receive"

2020-10-20 22:27 UTC, ThrawnCA commented on src/components/topics-list.js
> +            title: 'Clean and santise',
Misspelled "sanitise"

2020-10-20 22:27 UTC, ThrawnCA commented on src/resources/overview/view.html
> +    Only dogs are allowed in outdoor dining areas if you as the business choose to allow them. Check with your
"Only dogs are allowed" should be "Dogs are only allowed"

2020-10-20 22:27 UTC, ThrawnCA commented on src/resources/questions-health-hygiene/question-8/no.html
> +   A staff illness policy or procedure helps you to:
This sentence is incomplete.

2020-10-20 22:27 UTC, ThrawnCA commented on src/resources/summary/animal-pests-section1/view.html
> +    Thank you for taking the time to complete the Animals and pests
Inconsistent capitalisation.

2020-10-27 02:55 UTC, duttonw commented on src/resources/home/view.html
> +                <img src="https://www.qld.gov.au/dev/food-pantry/dev/kyfb-home-images/Skills-and-knowledge-176606698.jpg" alt="">
unsure, may want to be relative or prd version of images

2020-10-27 02:57 UTC, duttonw approved these changes
Will merge, please correct what has been raised

2020-10-27 02:58 UTC, merged